### ISSUE TITLE
Should we use the & syntax for function definition in "Funky Functions"?

### ISSUE THREAD

**Issue by radar** [radar/joyofelixir#11]
In Funky Functions we show that you can define a method using this code:

```
iex> greeting = fn (place) -> "Hello, #{place}!" end
```

But you could also do:

```
iex> greeting = &("Hello, #{&1}!")
```

**Comment by blackdahila** [comment]
But it's ugly 😿

**Comment by chadoh** [comment]
I like it. Also, the [Elixir docs](https://hexdocs.pm/elixir/Enum.html#sort/2) seem to use this format in their examples, so the Elixir newbies will need to know this format soon enough. Best that the newbies know about this syntax before they go out to the big wide overwhelming world.

**Comment by radar** [comment]
I think it's sensible and worth explaining to beginners, as they're going to see it in other people's Elixir code eventually and wonder what it is.

It's now explained in toward the end of Chapter 5, and I added a little bit of extra content in Chapter 9 that explains the `&IO.puts/1` syntax using the same terms.
