### ISSUE TITLE
Chapter 3

### ISSUE THREAD

**Issue by ShalokShalom** [radar/joyofelixir#22]
https://joyofelixir.com/3-lovely-lists/4

those_who_are_assembled = adds firstly a couple of persons, then just one.
This is confusing since I like to know how to make multiple sublists at once. 

Plus, it also suggests that people can get added to such lists after a while, without mentioning how.

**Comment by radar** [comment]
The second definition of `those_who_are_assembled` creates a new list. 

I will update the second example to show adding two people:

```
iex> those_who_are_assembled = [
...> ["Roberto", "30ish", "Male"],
...> ["The Author", "30ish", "Male"],
...> ]
```

People can't get added to lists; everything in Elixir is immutable. To "add" them to the list you would need to create a new list.

```
[["A new person", "40", "Female"] | those_who_are_assembled]
```

This may be something worthwhile showing so I will make a note of that.
