### ISSUE TITLE
Chapter 5

### ISSUE THREAD

**Issue by ShalokShalom** [radar/joyofelixir#24]
https://joyofelixir.com/5-funky-functions/

I suggest doing an example with numbers if you like the users to calculate things.

In general, i stock here: 
![screenshot_20170813_100315](https://user-images.githubusercontent.com/6344099/29254530-06017618-8097-11e7-8cc6-525d5141c2e6.png)

**Comment by radar** [comment]
Done in 4e88b34.

Thanks!

**Comment by ShalokShalom** [comment]
4e88b34?
