### ISSUE TITLE
Chapter 6 - Pattern Matching - too detailed?

### ISSUE THREAD

**Issue by radar** [radar/joyofelixir#3]
Is this chapter too detailed? Does it spend too long talking about pattern matching? Or is it necessary to talk about pattern matching for this long, showing the different ways of matching things in Elixir?

**Comment by blackdahila** [comment]
For me, who knows what pattern match is it is too detailed. If I was about to get to know a little about matching in Elixir I wouldn't read this all. 
A few suggestions:
At the beginning, I would describe what pattern matching is with details and some examples written in some sketchy way. And then I would show some code. I would also omit the last `match everything` section and bind it with the previous ones.

**Comment by radar** [comment]
I think Chapter 6 is fine now.
