### ISSUE TITLE
Not very colorblind-friendly

### ISSUE THREAD

**Issue by akrejczinger** [radar/joyofelixir#32]
I have a slight case of deuteranopia and it's impossible for me to differentiate the green and yellow colors used for syntax highlighting in this book. This website hopefully lets non-colorblind people see the issue as well: https://www.toptal.com/designers/colorfilter?orig_uri=https://joyofelixir.com/2-where-did-i-put-that-value/&process_type=deutan
Not a critical issue though.

**Comment by radar** [comment]
Hey @akrejczinger, thanks for filing an issue! These are the default colours that I see from iex in iTerm. I think changing them would be confusing for others, so I will keep them as is.

Thank you for filing an issue anyway!
