### ISSUE TITLE
Errata: Funky Functions

### ISSUE THREAD

**Issue by chadoh** [radar/joyofelixir#36]
Unintentional `>`:

>  multiply (`*>`) it by 1.8

---

> Exercises
> * Make a function which turns fahrenheit temperatures into celcius.
> * Make a function which returns the number of seconds in the specified amount of days. For example, seconds.(2) should tell us how many seconds there are in 2 days.
> * Make a function which takes two maps with "age" keys in them and returns the average age.
> * Save either of these ~two~ _three_ solutions in their own file and run them through the elixir command-line tool.

**Comment by radar** [comment]
Thanks @chadoh :) 

Would you mind opening a PR to fix this and #34 and #35?

**Comment by chadoh** [comment]
Yeah, I can do that

**Comment by chadoh** [comment]
Eeek, you write the chapters in raw HTML and not with markdown?? 😱

**Comment by radar** [comment]
Sure do! It’s because I want lots of control over how the code is presented.
