### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by radar** [radar/joyofelixir#4]
Every good book has a good logo. I sent @baweaver some sketches 

![19894521_10211536291216426_1410100878_n](https://user-images.githubusercontent.com/2687/28343725-23453de8-6c62-11e7-9416-c8d2c45233a1.jpg)

And he sent some back:

![19832513_10213222779784510_780680471_n](https://user-images.githubusercontent.com/2687/28343729-271a46e8-6c62-11e7-9801-49f8b95f4f90.jpg)

**Comment by meshy** [comment]
Looks familiar...

![http://www.lexcorp.ca/images/vancouverdrupaldeveloper/drupal-logo.png](http://www.lexcorp.ca/images/vancouverdrupaldeveloper/drupal-logo.png)

**Comment by radar** [comment]
It is not the Drupal logo. Any resembelance is unintentional. 

PS mine looks better
