### ISSUE TITLE
Errata: seasons should NOT be capitalized

### ISSUE THREAD

**Issue by chadoh** [radar/joyofelixir#41]
In ch9:

> The names of these seasons should be capitalized because they are nouns, but whoever created this list neglected to capitalize them. Oops! What we should have is a list with proper capitalization:

Two problems with this:

1. Unlike German, generic nouns are not capitalized in English. If they were, the sentence above would read like this: "The Names of these Seasons should be capitalized because they are Nouns, but Whoever created this List neglected to capitalized them." In English, we only capitalize _proper_ nouns, like the names of people, places, and for some reason, days of the week and months.
2. The names of the seasons are not proper nouns. As such, they are only capitalized when they are part of the titles of things and whatnot. [More info](https://english.stackexchange.com/questions/39448/are-particular-seasons-proper-nouns).

## Options for fixing

I think we have two options for how to fix this:

1. Remove that line, and just say something like "Management has told us that they want these seasons to be capitalized," or just "So this is the list we want to make:" (keeping in mind that you've already talked for a while about wanting to capitalize each item in this list)
2. Use days of the week or months or some other _proper_ noun instead of seasons. Then change the sentence in question to say "proper nouns" instead of just "nouns"

**Comment by radar** [comment]
It appears you're right! I think I've been capitalising them all my life without really giving it much thought.

I think you're right that using days of the week or months would work better here :)
