### ISSUE TITLE
Chapter 10: no details on where to find functions on our own

### ISSUE THREAD

**Issue by chadoh** [radar/joyofelixir#43]
At the beginning of the chapter, it says:

> You'll then see where you can find functions on your own, outside of this book in the big wide world.

But then it jumps right from talking about `Map.put/2` to "Exercises." The exercises _talk_ about finding a function in `Enum`, but never explicitly say how to find such functions.

**Comment by radar** [comment]
Chapter 10 seems to not include this text anymore.
