### ISSUE TITLE
Chapter 10: false claims about the keys in a map having order

### ISSUE THREAD

**Issue by chadoh** [radar/joyofelixir#45]
> Our data is back into the shape of a map... but the days of the week have lost their ordering. That'll be a problem that I'll leave as an exercise for you to fix at the end of this chapter.

> Can you find a function in `Enum` that would let us output the days of the week and their temperatures in the right order?

Taken together, these two parts of the chapter made me, an experienced programmer but newbie Elixirite, think that maybe I was supposed to make a Map with correctly-ordered keys. But the keys of a map are unordered!

I think it's worth re-stressing that the order of keys in a map cannot be relied upon, and that if the order is important to use a List instead.

In fact, the only solution I figured out so far is to output the result as a List of Tuples, rather than a Map. My approach looks like this:

```elixir
%{
  "Monday" => 28,
  "Tuesday" => 29,
  "Wednesday" => 29,
  "Thursday" => 24,
  "Friday" => 16,
  "Saturday" => 16,
  "Sunday" => 20
}
|> Enum.map(fn ({day, temp}) -> {day, temp * 1.8 + 32} end)
|> Enum.sort_by(fn ({day, temp}) -> day_to_num.(day) end) # the implementation of `day_to_num` is left as an exercise for the reader ;)
|> IO.inspect
```

Is this about what you expected?

**Comment by radar** [comment]
Looks like this has been fixed, probably in 5a25436f.
