### ISSUE TITLE
Chapter 9: Values in the code examples and the descriptions do not match up

### ISSUE THREAD

**Issue by Croccifixio** [radar/joyofelixir#47]
The __BYO functions__ section in chapter 9 explains how to multiply each number in a list of numbers using a custom function as the 2nd argument of `Enum.map/2`. The accompanying text states that each number in the list will be multiplied by __42__, but in the provided example, the multiplier used is __2__.

Below is the excerpt I'm referring to (emphasis mine):

> ```
> iex> numbers = [4, 8, 15, 16, 23, 42]
> ```
> And then we wanted to multiply each number by a different number, let's say __*42*__. We're lazy and we want the computer to do the heavy lifting, and so we can pass `Enum.map/2` a function of our own design to acheive this goal:
>
> ```
> iex> Enum.map(numbers, fn (number) -> number * 2 end)
> [8, 16, 30, 32, 46, 84]
> ```
>
> With our own function here, we're taking each element of the list — represented inside the function as the variable `number` — and then multiplying it by __*42*__. When `Enum.map/2` has finished going through the list, it outputs a new list showing us the result of running that function on all items in the list.

**Comment by radar** [comment]
Fixed in #48.
