### ISSUE TITLE
7-itermission-recap does not exist?

### ISSUE THREAD

**Issue by psychonout** [radar/joyofelixir#53]
Going from Chapter 8, the link lands at 404.
![image](https://user-images.githubusercontent.com/32778999/49328441-c2a15100-f579-11e8-9623-a6308f9c7161.png)
![image](https://user-images.githubusercontent.com/32778999/49328446-c92fc880-f579-11e8-8960-21dcd1300664.png)
thanks

**Comment by radar** [comment]
Thank you! I've just pushed up a fix for this. This problem should now be fixed on the live site too.
