### ISSUE TITLE
Conditionals / Flow Control

### ISSUE THREAD

**Issue by radar** [radar/joyofelixir#6]
I don't really have a place in the book for these yet. This issue is just to indicate that there _should_ probably be a place for them. Perhaps I could cover at least `case` in the pattern matching chapter?

**Comment by blackdahila** [comment]
That's a good idea to place them in pattern matching chapter. In the section with functions maybe?

**Comment by radar** [comment]
Chapter 12 of this book covers `if`, `unless`, `case`, `cond` and `with`.
