### ISSUE TITLE
Link to chapter 16 gives a 404

### ISSUE THREAD

**Issue by nielsbom** [radar/joyofelixir#62]
https://joyofelixir.com/16-testing-your-code

**Comment by nielsbom** [comment]
I see that this is working (although empty) https://joyofelixir.com/16-where-to-from-here/

**Comment by radar** [comment]
Hey Niels, thanks for letting me know. Everything after Chapter 14 is up in the air at this point in time. I’m still working my way through the end of the book at the moment. So that means chapters post-14 or any appendix-like material won’t be in its right place until the book is done-done.
