### ISSUE TITLE
Chapter 14 - Inspect result for person is wrong.

### ISSUE THREAD

**Issue by cdmoyer** [radar/joyofelixir#71]
The example is:
```
iex> %Person{first_name: "Izzy", last_name: "Bell"}
Person[Izzy Bell]
```

but the module defines the protocol with`      "Person[#{first_name} #{last_name}, #{location}]"`
so it should be:
```
iex> %Person{first_name: "Izzy", last_name: "Bell"}
Person[Izzy Bell, home]
```

**Comment by cdmoyer** [comment]
Created PR: https://github.com/radar/joyofelixir/pull/72

**Comment by radar** [comment]
Thank you!
