### ISSUE TITLE
Chapter 14 references examples that don't exist

### ISSUE THREAD

**Issue by dylbyl** [radar/joyofelixir#77]
https://joyofelixir.com/14-modules-and-structs

At one point, the text tells us to compile `light.exs`, which doesn't exist.

In the "How to tell functions apart" section, `Light.toggle/1` is referenced, but is never shown to the reader in any example.

I'm assuming you initially had an example in place other than the Person module, then missed these instances when you changed the example

**Comment by radar** [comment]
Thank you @dylbyl. You're right that I was previously using a `Light` module here instead. That'll be fixed soon.
