### ISSUE TITLE
Chapter 18: typo in word "shgould"

### ISSUE THREAD

**Issue by seniorihor** [radar/joyofelixir#93]
> And then that **shgould** make our test happy too!

https://joyofelixir.com/18-automated-testing/

**Comment by radar** [comment]
Hey @seniorihor! Thank you very much for filing all of these typo issues. I've just swept through them today to fix them up in a few separate commits.

**Comment by seniorihor** [comment]
@radar It's my pleasure! Thank you for a great time reading your book 🙌
